name: Deploy static website to S3

on:
  push:
    branches:
      - main  # runs this workflow when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Create S3 bucket (if not exists)
      - name: Create S3 bucket
        run: |
          BUCKET_NAME=food-frontend-esther${{ github.actor }}
          aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null || \
          aws s3 mb s3://$BUCKET_NAME --region ${{ secrets.AWS_REGION }}
          echo "Bucket name: $BUCKET_NAME"

      # Step 4: Deploy files to S3
      - name: Upload website files
        run: |
          BUCKET_NAME=food-frontend-esther${{ github.actor }}
          aws s3 sync . s3://$BUCKET_NAME --delete --exclude ".git/*" --exclude ".github/*"
      
      # Step 5: Enable static website hosting
      - name: Enable static website hosting
        run: |
          BUCKET_NAME=food-frontend-esther${{ github.actor }}
          aws s3 website s3://$BUCKET_NAME/ --index-document index.html --error-document index.html

      # Step 6: Make bucket public
      - name: Set public read policy
        run: |
          BUCKET_NAME=food-frontend-esther${{ github.actor }}
          POLICY=$(cat <<EOF
          {
            "Version": "2012-10-17",
            "Statement": [{
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
            }]
          }
          EOF
          )
          echo "$POLICY" > policy.json
          aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy file://policy.json

      # Step 7: Display public website URL
      - name: Show website URL
        run: |
          echo "✅ Website URL: http://food-frontend-esther${{ github.actor }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com"
